name: burningbros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: domain
  data:
    path: data
  shared:
    path: shared

  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  intl: ^0.19.0
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator:
  flutter_gen_runner:

flutter_gen:
  output: lib/resources/
  line_length: 100 # Optional (default: 80)

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_intl:
  enabled: false